### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by apoorvam** [getgauge-contrib/gauge-go#1]
- [ ] Add data accessor methods for table type

- [x] Update example template

- [x] Gauge implementations in multiple packages should be honored

- [x] Change Describe to Step

- [x] Add make.go to generate and install `gauge-go` plugin on all platforms

- [x] Update proto messages and add `genproto.sh` 

- [x] Update README with build and install instructions

- [x] Add User docs

- [ ] Method params are always String

- [x] Add go build in startGo()

- [x] Add `godeps.json`

- [x] Should `error` be return type for hooks and Step?

- [x] Step executor should return failure details if step fails

- [x] Hook/Step should honor assert failures as step/hook failure

- [x] Add Gauge custom messages

- [x] Change github.com/manuviswam/gauge-go to github.com/getgauge-contrib/gauge-go

- [x] Change travis build to point to new repo

**Comment by apoorvam** [comment]
Moving a few of the tasks to new issue. Closing this for now.
